```{r}
data <- read.csv("~/nuig/courses 4th year/Semester 2/Project/GTEx aorta data/CIBERSORTx_Results_aorta.csv")
colnames(data)
```

```{r}
cibersort_results <- read.csv("~/nuig/courses 4th year/Semester 2/Project/GTEx aorta data/CIBERSORTx_Results_aorta.csv")
```


```{r}
cibersort_results
```

```{r}
colnames(cibersort_results)
```


VSMC_II
```{r}
# Load the necessary library
library(ggpubr)

# Create the scatter plot
p_VSMC_II <- ggscatter(data = cibersort_results, x = "Mid.age", y = "VSMC_II", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "spearman",
          main = "Cell type proportion according to age", xlab = "age", ylab = "VSMC_II
")
ggsave("C:\\Users\\lorca\\Documents\\Project\\1 Aorta\\p_VSMC_II.png", plot = p_VSMC_II)
```

```{r}
correlation_result <- cor.test(cibersort_results$VSMC_II, cibersort_results$Mid.age, method = "spearman")

p_value_VSMC_II <- correlation_result$p.value

print(p_value_VSMC_II)
```

VSMC_I
```{r}
# Load the necessary library
library(ggpubr)

# Create the scatter plot
p_VSMC_I <- ggscatter(data = cibersort_results, x = "Mid.age", y = "VSMC_I", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "spearman",
          main = "Cell type proportion according to age", xlab = "age", ylab = "VSMC_I
")
ggsave("C:\\Users\\lorca\\Documents\\Project\\1 Aorta\\p_VSMC_I.png", plot = p_VSMC_I)
```
```{r}
correlation_result <- cor.test(cibersort_results$VSMC_I, cibersort_results$Mid.age, method = "spearman")

p_value_VSMC_I <- correlation_result$p.value

print(p_value_VSMC_I)
```

Endothelial_I
```{r}
# Load the necessary library
library(ggpubr)

# Create the scatter plot
p_Endothelial_I <- ggscatter(data = cibersort_results, x = "Mid.age", y = "Endothelial_I", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "spearman",
          main = "Cell type proportion according to age", xlab = "age", ylab = "Endothelial_I
")
ggsave("C:\\Users\\lorca\\Documents\\Project\\1 Aorta\\p_Endothelial_I.png", plot = p_Endothelial_I)
```
```{r}
correlation_result <- cor.test(cibersort_results$Endothelial_I, cibersort_results$Mid.age, method = "spearman")

p_value_Endothelial_I <- correlation_result$p.value

print(p_value_Endothelial_I)
```

Endothelial_II
```{r}
# Load the necessary library
library(ggpubr)

# Create the scatter plot
p_Endothelial_II <- ggscatter(data = cibersort_results, x = "Mid.age", y = "Endothelial_II", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "spearman",
          main = "Cell type proportion according to age", xlab = "age", ylab = "Endothelial_II
")
ggsave("C:\\Users\\lorca\\Documents\\Project\\1 Aorta\\p_Endothelial_II.png", plot = p_Endothelial_II)
```
```{r}
correlation_result <- cor.test(cibersort_results$Endothelial_II, cibersort_results$Mid.age, method = "spearman")

p_value_Endothelial_II <- correlation_result$p.value

print(p_value_Endothelial_II)
```

Fibroblast_I
```{r}
# Load the necessary library
library(ggpubr)

# Create the scatter plot
p_Fibroblast_I <- ggscatter(data = cibersort_results, x = "Mid.age", y = "Fibroblast_I", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "spearman",
          main = "Cell type proportion according to age", xlab = "age", ylab = "Fibroblast_I
")
ggsave("C:\\Users\\lorca\\Documents\\Project\\1 Aorta\\p_Fibroblast_I.png", plot = p_Fibroblast_I)
```
```{r}
correlation_result <- cor.test(cibersort_results$Fibroblast_I, cibersort_results$Mid.age, method = "spearman")

p_value_Fibroblast_I <- correlation_result$p.value

print(p_value_Fibroblast_I)
```

Fibroblast_II
```{r}
# Load the necessary library
library(ggpubr)

# Create the scatter plot
p_Fibroblast_II <- ggscatter(data = cibersort_results, x = "Mid.age", y = "Fibroblast_II", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "spearman",
          main = "Cell type proportion according to age", xlab = "age", ylab = "Fibroblast_II
")
ggsave("C:\\Users\\lorca\\Documents\\Project\\1 Aorta\\p_Fibroblast_II.png", plot = p_Fibroblast_II)
```
```{r}
correlation_result <- cor.test(cibersort_results$Fibroblast_II, cibersort_results$Mid.age, method = "spearman")

p_value_Fibroblast_II <- correlation_result$p.value

print(p_value_Fibroblast_II)
```

Pericyte   
```{r}
# Load the necessary library
library(ggpubr)

# Create the scatter plot
p_Pericyte <- ggscatter(data = cibersort_results, x = "Mid.age", y = "Pericyte", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "spearman",
          main = "Cell type proportion according to age", xlab = "age", ylab = "Pericyte
")
ggsave("C:\\Users\\lorca\\Documents\\Project\\1 Aorta\\p_Pericyte.png", plot = p_Pericyte)
```
```{r}
correlation_result <- cor.test(cibersort_results$Pericyte, cibersort_results$Mid.age, method = "spearman")

p_value_Pericyte <- correlation_result$p.value

print(p_value_Pericyte)
```

X_        
```{r}
# Load the necessary library
library(ggpubr)

# Create the scatter plot
p_X_ <- ggscatter(data = cibersort_results, x = "Mid.age", y = "X_", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "spearman",
          main = "Cell type proportion according to age", xlab = "age", ylab = "X_
")
ggsave("C:\\Users\\lorca\\Documents\\Project\\1 Aorta\\p_X_.png", plot = p_X_)
```
```{r}
correlation_result <- cor.test(cibersort_results$X_, cibersort_results$Mid.age, method = "spearman")

p_value_X_ <- correlation_result$p.value

print(p_value_X_)
```

Neuron     
```{r}
# Load the necessary library
library(ggpubr)

# Create the scatter plot
p_Neuron <- ggscatter(data = cibersort_results, x = "Mid.age", y = "Neuron", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "spearman",
          main = "Cell type proportion according to age", xlab = "age", ylab = "Neuron
")
ggsave("C:\\Users\\lorca\\Documents\\Project\\1 Aorta\\p_Neuron.png", plot = p_Neuron)
```
```{r}
correlation_result <- cor.test(cibersort_results$Neuron, cibersort_results$Mid.age, method = "spearman")

p_value_Neuron <- correlation_result$p.value

print(p_value_Neuron)
```

Macrophage
```{r}
# Load the necessary library
library(ggpubr)

# Create the scatter plot
p_Macrophage <- ggscatter(data = cibersort_results, x = "Mid.age", y = "Macrophage", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "spearman",
          main = "Cell type proportion according to age", xlab = "age", ylab = "Macrophage
")
ggsave("C:\\Users\\lorca\\Documents\\Project\\1 Aorta\\p_Macrophage.png", plot = p_Macrophage)
```
```{r}
correlation_result <- cor.test(cibersort_results$Macrophage, cibersort_results$Mid.age, method = "spearman")

p_value_Macrophage <- correlation_result$p.value

print(p_value_Macrophage)
```

Mesothelial
```{r}
# Load the necessary library
library(ggpubr)

# Create the scatter plot
p_Mesothelial <- ggscatter(data = cibersort_results, x = "Mid.age", y = "Mesothelial", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "spearman",
          main = "Cell type proportion according to age", xlab = "age", ylab = "Mesothelial
")
ggsave("C:\\Users\\lorca\\Documents\\Project\\1 Aorta\\p_Mesothelial.png", plot = p_Mesothelial)
```
```{r}
correlation_result <- cor.test(cibersort_results$Mesothelial, cibersort_results$Mid.age, method = "spearman")

p_value_Mesothelial <- correlation_result$p.value

print(p_value_Mesothelial)
```

Lymphocyte
```{r}
# Load the necessary library
library(ggpubr)

# Create the scatter plot
p_Lymphocyte <- ggscatter(data = cibersort_results, x = "Mid.age", y = "Lymphocyte", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "spearman",
          main = "Cell type proportion according to age", xlab = "age", ylab = "Lymphocyte
")
ggsave("C:\\Users\\lorca\\Documents\\Project\\1 Aorta\\p_Lymphocyte.png", plot = p_Lymphocyte)
```
```{r}
correlation_result <- cor.test(cibersort_results$Lymphocyte, cibersort_results$Mid.age, method = "spearman")

p_value_Lymphocyte <- correlation_result$p.value

print(p_value_Lymphocyte)
```

Lymphatic_Endothelial
```{r}
# Load the necessary library
library(ggpubr)

# Create the scatter plot
p_Lymphatic_Endothelial <- ggscatter(data = cibersort_results, x = "Mid.age", y = "Lymphatic_Endothelial", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "spearman",
          main = "Cell type proportion according to age", xlab = "age", ylab = "Lymphatic_Endothelial
")
ggsave("C:\\Users\\lorca\\Documents\\Project\\1 Aorta\\p_Lymphatic_Endothelial.png", plot = p_Lymphatic_Endothelial)
```
```{r}
correlation_result <- cor.test(cibersort_results$Lymphatic_Endothelial, cibersort_results$Mid.age, method = "spearman")

p_value_Lymphatic_Endothelial <- correlation_result$p.value

print(p_value_Lymphatic_Endothelial)
```

```{r}
colnames(cibersort_results)
```


```{r}
pvalues <- c(p_value_VSMC_I, p_value_VSMC_II, p_value_Endothelial_I, p_value_Endothelial_II, p_value_Fibroblast_I, p_value_Fibroblast_II, p_value_Pericyte, p_value_X_, p_value_Neuron, p_value_Macrophage, p_value_Mesothelial, p_value_Lymphocyte, p_value_Lymphatic_Endothelial)

p.adjust(pvalues,method="bonferroni")
```
no significant correlation for all except => VSMC_II 

```{r}
pvalues <- c(p_value_VSMC_I, p_value_VSMC_II, p_value_Endothelial_I, p_value_Endothelial_II, p_value_Fibroblast_I, p_value_Fibroblast_II, p_value_Pericyte, p_value_X_, p_value_Neuron, p_value_Macrophage, p_value_Mesothelial, p_value_Lymphocyte, p_value_Lymphatic_Endothelial)

p.adjust(pvalues,method="BH")
```
no significant correlation for all except => VSMC_II 

```{r}
library(tidyr)
data_long <- cibersort_results %>%
  pivot_longer(cols = c("VSMC_I", "VSMC_II", "Endothelial_I", "Endothelial_II", "Fibroblast_I", "Fibroblast_II", "Pericyte", "Macrophage", "Mesothelial"), names_to = "Cell_Type", values_to = "Fraction")
##removing O
```

```{r}
data_long
```

```{r}
library(viridis)

# Generate a sequence of colors using the viridis palette
colors <- viridis(20)

library(dplyr)
p <- data_long %>%
  group_by(AGE,Cell_Type) %>%
  summarise(mf = mean(Fraction)) %>%
  ungroup()%>%
  ggplot(aes(y = AGE, x = mf, fill = Cell_Type)) +
  geom_bar(stat = "identity") +
  scale_fill_viridis_d() +
  labs(title = "Cellular composition according to age", y = "Age", x = "Fraction of Cell Types", size = 20) +
  theme_minimal() +
  coord_flip() 

p


p <- recordPlot()
png("C:\\Users\\lorca\\Documents\\Project\\1 Aorta\\p_Aorta_Cell_Comp.png", width = 6, height = 4, units = "in", res = 800)
replayPlot(p)
dev.off()

```

```{r}
p_age <- barplot(table(cibersort_results$AGE), 
                 main = "Age of our samples",
                 xlab = "Age",
                 ylab = "Number of samples")

p_age <- recordPlot()
png("C:\\Users\\lorca\\Documents\\Project\\1 Aorta\\p_Aorta_Age_Nb.png", width = 6, height = 4, units = "in", res = 800)
replayPlot(p_age)
dev.off()
```
```{r}
# Calculate the total number of samples
total_samples <- sum(table(cibersort_results$AGE))

# Print the total number of samples
cat("Total samples:", total_samples, "\n")

```









