```{r}
library(biomaRt)
library(immunedeconv)
library(corrplot)
library(forcats)
library(stringr)
library(here)
library(dplyr)
library(tidyr)
library(ggplot2)
library(RColorBrewer)
library(CePa)
library(ensembldb)
library(EnsDb.Hsapiens.v86)
library(gridExtra)
```

```{r}
setwd("C:\\Users\\lorca\\Documents\\Project\\2 Liver\\Liver_")
```

```{r}
gct_liver <- read.table("gene_tpm_liver.gct", header = TRUE, sep = "\t", skip = 2, stringsAsFactors = FALSE)
```


```{r}
gct_liver
```

```{r}
colnames(gct_liver) <- gsub("\\.", "-", colnames(gct_liver))
colnames(gct_liver) <- gsub("GTE", "GTEX", colnames(gct_liver))
cols <- colnames(gct_liver)[3:ncol(gct_liver)]
test <- str_split_fixed(cols, "-", n = 5)[,1:2]
test <- paste("GTEX", str_split_fixed(cols, "-", n = 5)[,2], sep = "-")
test
```

```{r}
colnames(gct_liver)[3:ncol(gct_liver)] <- test
```


```{r}
gct_liver[1:5, 1:6]
```


```{r}
colnames(gct_liver)[3] <- "gene_name"
colnames(gct_liver)[2] <- "gene_id"
```

```{r}
gct_liver <- gct_liver[,-1] ##to delete column 1
gct_liver
```


```{r}
gct_liver2 <- gct_liver[, -1]
names(gct_liver2)[1] <- "Genes"
gct_liver2
```



```{r}
Liver_TPM2 <- gct_liver2
Liver_TPM2
```




```{r}
write.table(Liver_TPM2, "C:\\Users\\lorca\\Documents\\Project\\2 Liver\\Liver_\\Liver_TPM2.txt", sep = "\t", quote = FALSE, row.names = FALSE)
```













